# :: Zplug - ZSH plugin manager
export ZPLUG_HOME=$HOME/.zplug

# Check if zplug is installed
if [[ ! -d $ZPLUG_HOME ]]; then
  git clone https://github.com/zplug/zplug $ZPLUG_HOME
  source $ZPLUG_HOME/init.zsh && zplug update
fi

# Essential
source $ZPLUG_HOME/init.zsh


# Zplug plugins
zplug "zplug/zplug", hook-build:"zplug --self-manage"

# zplug modules to be installed
source $HOME/.dotfiles/zshconf/modules.zsh

# zsh modules configuration
source $HOME/.dotfiles/zshconf/conf.zsh

# Load everything
zplug load
